server.servlet.encoding.force-response: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: blogAdmin
    password: c20021217
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
  mustache:
    servlet:
      expose-session-attributes: true